name: Pipeline 1 - Deploy CSS

on:
  push:
    paths:
      - 'style.css'

jobs:
  deploy-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log Deployed File
        run: |
          echo "Deploying CSS changes..."
          ls -l style.css
